language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install



before_script:
  - git clone https://github.com/pinggod/hexo-theme-jekyll.git themes/jekyll
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "jys0909"
  - git config user.email "276977683@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/jys0909/ysblog.git