# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: 新浪
    url: https://sina.com
  - name: 搜狐
    url: https://souhu.com/
  - name: 好123
    url: https://hao123.com/
  - name: Simon
    url: https://jys0909.github.io/

# navigation menu
menu:
  - name: 首页
    slug: home
    url: /
  - name: 档案
    slug: archives
    url: /archives
  - name: Gallery
    slug: gallery
    url: /gallery
  - name: 关于
    slug: about
    url: /about

# widgets
widgets:
  - 关于
  - 友情链接
  - 分类
  - 标签

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/stkevintan
- slug: twitter
  url: https://twitter.com/kevinsfork
- slug: rss
	url: /atom.xml
